### ISSUE TITLE
Attempting to run js driven animation on animation node

### ISSUE THREAD

**Issue by poupryc** [charpeni/react-native-speech-bubble#2]
Hello,

I tried to run this, as in the example :

`<SpeechBubble
  speeches={[ 'String 1', 'String 2', 'String 3' ]}
/>`

But I get this error:

`attempting to run js driven animation on animation node that has been moved to "native" earlier by starting an animation with 'useNativeDriver: true'`

I think it's an incompatibility between the version of React and your module. It's sad because I think I could have built cool things

Hopefully it will be settled in a future release !

**Comment by charpeni** [comment]
Thanks for reaching out, I'll check that.

In the meantime, PRs are welcome if you find a fix.

**Comment by poupryc** [comment]
![screenshot_1490283084](https://cloud.githubusercontent.com/assets/25421857/24256191/c2802ddc-0fe7-11e7-97e7-c85855ff0ea7.png)
Thank you for your attention and your response,

I unfortunately do not yet have the level to fully understand react-native. So I would wait for the patch if there is one. 

Thank you ^^

PS: If you want, I can transfer the debug log of my app.

**Comment by poupryc** [comment]
Maybe this [page](https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html) or [this](http://stackissue.com/facebook/react-native/nativeanimation-problems-solutions-9120.html) could help you ^^

(As you can see, I really want to use this module for my dialogues, because there are no similar modules)

Maybe looking at the code [fork](https://github.com/JonathanWi/react-native-speech-bubble) would be a good start?

**Comment by charpeni** [comment]
Thank you for the information.

This should be fixed by commit 4dbb58900027e36f3abd595a1eed6c2af4320b7d, it's already available on npm as `0.3.0`. 🚀 

I will close this issue, but if there is anything else feel free to ping me.
